#!/bin/zsh

# Add a bunch of function paths, including OS-specific ones and, if necessary,
# zsh vcs-info functions. Finally, mark everything currently in $fpath as setup
# for autoload. This may be done more than once during setup, but we need it
# for some of the steps that follow.
#
# As to the vcs-info functions, versions of Zsh prior to 4.3.10 doesn't support
# %u/%c for un/staged characters. So let's use these 4.3.11 versions that I
# pulled in from the zsh source (vendored in vendor/zsh). 4.3.6 seems like a
# safe point to stop including, at least for now.
fpath=(~/.zsh/functions ~/.zsh/prompts ${fpath})

if [[ -d ~/.zsh/${OSTYPE}/functions ]]; then
  fpath=(~/.zsh/${OSTYPE}/functions ${fpath})
fi

if is-at-least 4.3.6 && ! is-at-least 4.3.11; then
  fpath=(~/.zsh/vcs-info ${fpath})
fi

autoload -U ${^fpath}/*(N.:t)
