#!/bin/zsh

typeset -A __hzsh_known_zsh_options
__hzsh_known_zsh_options=($(builtin set -o))

function hz_setopt()
{
  local opt_name=$(echo ${(L)1#no_#} | sed -e 's/_//')
  if [ -n "${__hzsh_known_zsh_options[${opt_name}]}" ]; then
    builtin setopt ${1}
  fi
}

# Reorganized to match the zshoptions manpage; rather than ordering by
# alphabetical sort, ordered by alphabetical within the logical groups.

# [ changing directories ]
hz_setopt auto_cd                  # cd 'path' if 'path' is given as a command.
hz_setopt auto_pushd               # cd = pushd
hz_setopt no_cdable_vars           # don't try to expand as ~path
hz_setopt no_chase_dots            # foo/bar/.. is foo/ even if bar is a symlink
hz_setopt chase_links              # cd to a symlink is in fact cd to the true dir
hz_setopt pushd_ignore_dups        # ignore dups in pushd
hz_setopt no_pushd_minus           # don't exchange +/-
hz_setopt pushd_silent             # don't print stack after push/pop
hz_setopt pushd_to_home            # pushd == pushd $HOME

# [ completion ]
hz_setopt no_always_last_prompt    # Completions return to last prompt if numeric.
hz_setopt always_to_end            # Always go to end of word after completion.
hz_setopt auto_list                # list choice on ambiguous command
hz_setopt auto_menu                # show menu for completion
hz_setopt no_autoname_dirs         # Dir params are explicit ~param. RTFM.
hz_setopt auto_param_keys          # Remove trailing spaces on param name completion
hz_setopt auto_param_slash         # add slash for directories
hz_setopt auto_remove_slash        # remove slash on dirs if word separator added
hz_setopt no_bash_auto_list        # auto_list is sufficient, i want it on first tab
hz_setopt complete_aliases         # don't replace alias before completion
hz_setopt complete_in_word         # completion to be done from cursor in word
hz_setopt no_glob_complete         # don't generate matches and cycle through them
hz_setopt hash_list_all            # verify path hash on completion
hz_setopt list_ambiguous           # unambiguous prefix completion is done silently
hz_setopt no_list_beep             # don't beep for completion
hz_setopt list_packed              # different width for completion
hz_setopt no_list_rows_first       # sort by columns
hz_setopt list_types               # show types of listing files
hz_setopt no_menu_complete         # don't show menu on ambiguous completion
hz_setopt no_rec_exact             # recognize exact match even if ambiguous

# [ expansion and globbing ]
hz_setopt bad_pattern              # warn on bad file patterns
hz_setopt bare_glob_qual           # () is qualifier list
hz_setopt brace_ccl                # expand {adasd} to (a, d, s)
hz_setopt case_glob                # case sensitive globbing
hz_setopt no_csh_null_glob         # don't erase not matched globs silently
hz_setopt equals                   # perform '=' file expansions
hz_setopt extended_glob            # #,~,^ expansion
hz_setopt glob                     # sure i want globbing
hz_setopt no_glob_assign           # no globbing on foo=*, use foo=(*)
hz_setopt no_glob_dots             # foo won't match .foo
hz_setopt no_glob_subst            # no recursive expansion

hz_setopt no_hist_subst_pattern    # history substitution uses string matching
hz_setopt no_ignore_braces         # do braces expansion
hz_setopt no_ksh_glob              # ignore @ before ()
hz_setopt magic_equal_subst        # foo= is file expanded
hz_setopt mark_dirs                # adds / on dirs in filename completion
hz_setopt multibyte                # respect multibyte characters when found
hz_setopt nomatch                  # print error on non matched patterns (!!!)
hz_setopt no_null_glob             # don't delete not matched globs
hz_setopt numeric_glob_sort        # sort in numeric order rather than lexicographic
hz_setopt rc_expand_param          # foo${xx}bar where xx is (a b c) = fooabar ...
hz_setopt no_sh_glob               # allow globbing with [(|)<]
hz_setopt unset                    # unset parameters are empty, not parameters.
hz_setopt no_warn_create_global    # No warning on assigned global param in function.

# [ history ]
hz_setopt append_history           # append to history, don't truncate it
hz_setopt bang_hist                # csh-style history expansion with '!'
hz_setopt extended_history         # timestamped history :time:elapsed:command
hz_setopt hist_allow_clobber       # add | to redirections in history
hz_setopt no_hist_beep             # don't beep on history expansion errors
hz_setopt hist_expire_dups_first   # remove dups from history first
hz_setopt hist_find_no_dups        # don't show dups even if not contiguous
hz_setopt hist_ignore_all_dups     # ignore all -- even non contiguous -- dups
hz_setopt hist_ignore_dups         # ignore contiguous dups
hz_setopt no_hist_ignore_space     # store commands that match /^ /
hz_setopt hist_no_functions        # don't save functions defs in history
hz_setopt hist_no_store            # remove hists access cmds from hist
hz_setopt hist_reduce_blanks       # remove superfluous blanks
hz_setopt hist_save_by_copy        # prevents history loss
hz_setopt hist_save_no_dups        # no dups on history saving
hz_setopt hist_verify              # expands history into the edit buffer
hz_setopt inc_append_history       # append incrementally, not on exit
hz_setopt share_history            # Share history between sessions.

# [ initialization ]
hz_setopt no_all_export            # Parameters are not automatically exported
hz_setopt no_global_export         # local vars are not globals one
hz_setopt global_rcs               # use global rcs
hz_setopt rcs                      # source all /etc rcs

# [ input/output ]
hz_setopt aliases                  # expand aliases
hz_setopt clobber                  # redirection can create files
hz_setopt correct                  # try to correct command line
hz_setopt no_correct_all           # don't correct args
hz_setopt no_dvorak                # use only regular (qw|az)erty
hz_setopt no_flow_control          # ignore ^S/^Q
hz_setopt no_ignore_eof            # don't ignore ^D
hz_setopt interactive_comments     # allow comments in interactive shell (!!!)
hz_setopt hash_cmds                # do not always search through path, hash cmds
hz_setopt hash_dirs                # hash directories holding commands too
hz_setopt no_mail_warning          # auto-explained
hz_setopt path_dirs                # search in path even if cmd has '/' in it
hz_setopt print_eight_bit          # just to be sure
hz_setopt no_print_exit_value      # don't print non-zero exit values
hz_setopt rc_quotes                # '' == ' in 'quoted exprs
hz_setopt no_rm_star_silent        # ask user before rm foo/*
hz_setopt no_rm_star_wait          # don't idle 10 seconds
hz_setopt short_loops              # short loops
hz_setopt no_sun_keyboard_hack     # I don't use a SUN keyboard.

# [ job control ]
hz_setopt auto_continue            # send SIGCONT to jobs disowned
hz_setopt auto_resume              # single word resume if possible
hz_setopt no_bg_nice               # don't renice jobs in bg
hz_setopt check_jobs               # check jobs on exit
hz_setopt no_hup                   # don't SIGHUP bg cmds on logout
hz_setopt long_list_jobs           # list jobs in long format
hz_setopt monitor                  # job control
hz_setopt notify                   # notify immediately, not on next prompt

# [ prompting ]
hz_setopt no_prompt_bang           # don't perform history expansion in prompt
hz_setopt no_prompt_cr             # don't print \r before prompt ---> see precmd !
hz_setopt prompt_sp                # preserve partial line
hz_setopt prompt_percent           # expand % escapes in prompt
hz_setopt prompt_subst             # subst in prompt
hz_setopt transient_rprompt        # better for cut/paste

# [ scripts and functions ]
hz_setopt c_bases                   # understand 12#120 as 120 in base 12
#hz_setopt debug_before_cmd         # run DEBUG trap before command (ksh 93)
#hz_setopt no_debug_before_cmd      # run DEBUG trap after command (ksh 88)
#hz_setopt no_err_exit              # don't weant to see exit status even if nonzero
#hz_setopt no_err_return            # no return from a function with non 0 ending cmds
hz_setopt eval_lineno               # Track eval line numbers.
hz_setopt exec                      # sure we want to exec commands
hz_setopt function_argzero          # $0 == name of script
#hz_setopt local_options            # setopts are local to functions, func() only
#hz_setopt local_traps              # traps are local only
#hz_setopt multios                  # multi redirection allowed
#hz_setopt no_octal_zeroes          # 010 = 9 sucks
#hz_setopt typeset_silent           # Doesn't print
#hz_setopt verbose                  # Print input lines as they are read
#hz_setopt no_xtrace                # do not debug by default

# [ shell emulation ]
hz_setopt no_bsd_echo              # dont want BSD echo compat
hz_setopt no_csh_junkiehistory     # csh sucks
hz_setopt no_csh_junkie_loops      # want do /list/; done
hz_setopt no_csh_junkie_quotes     # csh quote rules sucks too
hz_setopt no_csh_nullcmd           # want to keep my (READ)?NULLCMD settings
hz_setopt no_ksh_arrays            # don't emulate ksh arrays
hz_setopt no_ksh_autoload          # don't do some dark autoload on function call
hz_setopt ksh_option_print         # modify hz_setopt output
hz_setopt no_ksh_typeset           # use zsh typeset
hz_setopt no_posix_builtins        # Don't use POSIX-style builtins.
hz_setopt no_posix_identifiers     # Don't use POSIX-style identifiers [a-zA-Z0-9_].
hz_setopt no_sh_file_expansion     # dont expand filnames first
hz_setopt no_sh_nullcmd            # use my NULLCMD
hz_setopt sh_option_letters        # interprete single option letters a la ksh
hz_setopt no_sh_word_split         # `s="a b"; a=($s)' => array of length 1, not 2
hz_setopt traps_async             # Handle traps immediately, not on child exit.

# [ shell state ]
#hz_setopt interactive             # Use the default
#hz_setopt login                   # Use the default
#hz_setopt privileged              # Use the default
#hz_setopt restricted              # Use the default
#hz_setopt shin_stdin              # Use the default
#hz_setopt single_command          # Use the default

# [ zle ]
hz_setopt beep                     # Beep on ZLE error.
hz_setopt no_emacs                 # Don't change this.
hz_setopt no_overstrike            # Don't start ZLE in overstrike mode
hz_setopt no_single_line_zle       # Use multiline editor
hz_setopt no_vi                    # Use bindkeys
hz_setopt zle                      # use zsh le

unfunction hz_setopt
unset __hzsh_known_zsh_options
