#! /bin/zsh

if has sudo; then
  alias su='export XAUTHORITY=${HOME}/.Xauthority; command sudo -s'
  alias sudo='export XAUTHORITY=${HOME}/.Xauthority; command sudo'
fi

alias du="du -hcs"
alias df="df -h"

if [ "${DISABLE_LS_COLORS}" != true ]; then
  if ls --color -d . &>/dev/null 2>&1; then
    alias ls='ls --color=tty -F'
  else
    alias ls='ls -GF'
  fi
else
  alias ls="ls -F"
fi

alias l="ls -lFh"
alias ll="ls -lAF"
alias la='ls -AF'
alias lla="ls -lAF"
alias lsf="ls -sF"
alias ltr="ls -ltrF"

alias ymd=yyyymmdd
alias ymd-hms=yyyymmdd-hhmmss

alias aliases=alias
alias h=history
alias j=jobs

alias cleanf='clean -f'
alias cleanrf='clean -rf'
alias keep='noglob keep'

# commands starting with % for pasting from web
alias %=' '

# shortened sudo, from oh-my-zsh
alias _='sudo'

autoload zmv
alias mmv='noglob zmv -W'

# commands starting with % for pasting from web
alias %=' '

# Suffix aliases for Ruby and Python so that they get run as if I had 'ruby' or
# 'python' in front of them.
alias -s rb=ruby
alias -s py=python

# Abuse the "open" command on OS X or *-open on Linux
declare -a __hzsh_extensions
declare __hzsh_extension
__hzsh_extensions=(mp3 wav aac ogg avi mp4 m4v mov qt mpg mpeg jpg jpeg png \
  psd bmp gif tif tiff eps ps pdf html)

for __hzsh_extension in ${__hzsh_extension}; do
  alias -s ${__hzsh_extension}=call-open
done

unset __hzsh_extensions __hzsh_extension

if not has seq && has gseq; then
  alias seq=$(which gseq)
fi
