#!/usr/bin/env ruby

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

def log_off
  puts "== Logging to log file."
  ActiveRecord::Base.logger.level = 1  # warn (?)
  nil
end

def log_on
  puts "== Logging to console."
  ActiveRecord::Base.logger.level = 0  # debug (?)
  nil
end
