#! zsh

typeset -ga zshaddhistory_functions

zshaddhistory_functions+='__hszsh_hwd_add_local_history'

typeset -ga __hszsh_hwd_local_history_files
function __hszsh_hwd_add_local_history()
{
  print -sr -- ${1%%$'\n'}

  if [ ${#__hszsh_hwd_local_history_files} -ne 0 ]; then
    fc -p "${__hszsh_hwd_local_history_files[-1]}"
  fi
}
