#!/bin/zsh

autoload colors zsh/terminfo
[[ "${terminfo[colors]}" -ge 8 ]] && colors

[ -z "${HOME}" ] && export HOME=$(cd ~; pwd)
[ -z "${HOSTNAME}" ] && export HOSTNAME=$(hostname)

export EMAIL="austin@halostatue.ca"
export FULLNAME="Austin Ziegler"

export IRCNICK=Austin__
export IRCNAME=${FULLNAME}
export IRCSERVER=irc.freenode.net
export IRC_SERVERS_FILE="${HOME}/.irc-serv"

export MANWIDTH=80

# less options
export LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export LSCOLORS="Gxfxcxdxbxegedabagacad"

# Still not *quite* sure I want to use lesspipe.
# if has lesspipe.sh; then
#   export LESS="-R -M --shift 5"                               
#   export LESSOPEN="|lesspipe.sh %s"
#   export LESSCOLOR=1
# fi

# These reserved name arrays allow chaining of preexec, precmd, and chpwd
# functions.
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

[ -w ${zsh_cache} ] && HISTFILE=${zsh_cache}/history

HISTSIZE=10000                  # size of history
SAVEHIST=10000                  # maximum of history events to be save

LOGCHECK=60                     # watch login/logout every 60 seconds
watch=(notme)                   # watch login/logout

LISTMAX=0                       # Ask only on scroll

NULLCMD='cat'                   # use cat for > null commands
READNULLCOMMAND='more'          # use more for < null commands

REPORTTIME=2                    # report time if execution exceeds amount of seconds

if is-interactive; then
 if has less; then
   export PAGER=less
 fi

 if has ack; then
   export ACK_OPTIONS="--color"
 fi

 alias grep='grep --color=auto'
fi
