#!/bin/zsh

[ -z "${HOME}" ] && export HOME=$(cd ~; pwd)
[ -z "${HOSTNAME}" ] && export HOSTNAME=$(hostname)

export __hzsh_dotfile_root=$(builtin echo ${0}(:A:h:h:h))
export __hzsh_package_root="${__hzsh_dotfile_root}/packages"
