#!/bin/zsh

[ -z "${HOME}" ] && export HOME=$(cd ~; pwd)
[ -z "${HOSTNAME}" ] && export HOSTNAME=$(hostname)

export EMAIL="austin@halostatue.ca"
export FULLNAME="Austin Ziegler"

export GIT_AUTHOR_NAME=${FULLNAME}
export GIT_COMMITTER_NAME=${FULLNAME}
export GIT_AUTHOR_EMAIL=${EMAIL}
export GIT_COMMITTER_EMAIL=${EMAIL}

export IRCNICK=Austin__
export IRCNAME=${FULLNAME}
export IRCSERVER=irc.freenode.net
export IRC_SERVERS_FILE="${HOME}/.irc-serv"

# export CVS_RSH="ssh"
# export CVSREAD=yes
export MANWIDTH=80

# export GTK_IM_MODULE=xim
# export LC_MESSAGES=C
# export LC_ALL=

# less options
export LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export ZMESSDIR=~/mess

# these are the default arguments to exuberant-ctags
# CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
