#! /bin/zsh

if has sudo; then
  alias su='export XAUTHORITY=${HOME}/.Xauthority; command sudo -s'
  alias sudo='export XAUTHORITY=${HOME}/.Xauthority; command sudo'
fi

alias du="du -hcs"
alias df="df -h"

alias ls="ls -F"
alias l="ls -lFh"
alias ll="ls -lAF"
alias la='ls -AF'
alias lla="ls -lAF"
alias lsf="ls -sF"
alias ltr="ls -ltrF"

alias ymd=yyyymmdd
alias ymd-hms=yyyymmdd-hhmmss

# cdd x will do cd ../x but with an absolute path
alias cdd="cd $(dirname $(pwd))"
alias ..='cd ..'

alias aliases=alias
alias h=history
alias j=jobs

alias cleanf='clean -f'
alias cleanrf='clean -rf'
alias keep='noglob keep'

# commands starting with % for pasting from web
alias %=' '

autoload zmv
alias mmv='noglob zmv -W'

# commands starting with % for pasting from web
alias %=' '

# Suffix aliases
alias -s rb=ruby
alias -s py=python

# alias -g CL="| wc -l"
# alias -g DN=/dev/null
# alias -g EG='|& egrep'
# alias -g EH='|& head'
# alias -g EL='|& less'
# alias -g ELS='|& less -S'
# alias -g ETL='|& tail -20'
# alias -g ET='|& tail'
# alias -g F=' | fmt -'
# alias -g G='| egrep'
# alias -g H='| head'
# alias -g HL='|& head -20'
# alias -g Sk="*~(*.bz2|*.gz|*.tgz|*.zip|*.z)"
# alias -g LL="2>&1 | less"
# alias -g L="| less"
# alias -g LS='| less -S'
# alias -g M='| more'
# alias -g NE="2> /dev/null"
# alias -g NS='| sort -n'
# alias -g NUL="> /dev/null 2>&1"
# alias -g PIPE='|'
# alias -g R=' > /c/aaa/tee.txt '
# alias -g RNS='| sort -nr'
# alias -g S='| sort'
# alias -g TL='| tail -20'
# alias -g T='| tail'
# alias -g US='| sort -u'
# alias -g VM=/var/log/messages
# alias -g X0G='| xargs -0 egrep'
# alias -g X0='| xargs -0'
# alias -g XG='| xargs egrep'
# alias -g X='| xargs'

# Abuse the "open" command on OS X or *-open on Linux
extensions=(mp3 wav aac ogg avi mp4 m4v mov qt mpg mpeg jpg jpeg png psd bmp \
  gif tif tiff eps ps pdf html)

if is-mac; then
  for ext in ${extensions[*]} dmg; do
    alias -s ${ext}=open
  done
else
  local _open

  if has gnome-open; then
    _open=gnome-open
  elif has xdg-open; then
    _open=xdg-open
  elif has kde-open; then
    _open=kde-open
  fi

  for ext in ${extensions[*]}; do
    alias -s ${ext}=${_open}
  done
fi
