#! /bin/zsh

if has xclip; then
  function xpwd()
  {
    echo "${PWD/${HOME}/~}" | xclip -i
    xclip -o
  }
  function xcd()
  {
    local d=$(xclip -o)
    echo ${d}
    eval cd "${d}"
  }
elif has pbpaste; then
  function xpwd()
  {
    echo "${PWD/${HOME}/~}" | pbcopy
    pbpaste
  }
  function xcd()
  {
    local d=$(pbpaste)
    echo ${d}
    eval cd "${d}"
  }
fi

# URL encode something and print it.
function url-encode
{
  setopt extendedglob
  echo "${${(j: :)@}//(#b)(?)/%$[[##16]##${match[1]}]}"
}

# Search google for the given keywords.
function google
{
  call-open "http://www.google.com/search?q=`url-encode "${(j: :)@}"`"
}
