#!/bin/zsh

[ x"${HOME}" = x ] && export HOME=$(cd ~; pwd)
[ x"$HOSTNAME" = x ] && export HOSTNAME=$(hostname)

export EMAIL="austin@halostatue.ca"
export FULLNAME="Austin Ziegler"

export GIT_AUTHOR_NAME=${FULLNAME}
export GIT_COMMITTER_NAME=${FULLNAME}
export GIT_AUTHOR_EMAIL=${EMAIL}
export GIT_COMMITTER_EMAIL=${EMAIL}

export IRCNICK=Austin__
export IRCNAME=${FULLNAME}
export IRCSERVER=irc.freenode.net
export IRC_SERVERS_FILE="${HOME}/.irc-serv"

# export CVS_RSH="ssh"
# export CVSREAD=yes
export MANWIDTH=80

# alternately 'mate -w'

# export INPUTRC="~/.inputrc"
# export MAIL="${HOME}/mail/inbox"

# export GTK_IM_MODULE=xim

# export LC_MESSAGES=C
# export LC_ALL=

add_paths_before_if() {
  for p in "${@}"; do
    [[ -d ${p} ]] && unique_path -b ${p}
  done
}

add_paths_after_if() {
  for p in "${@}"; do
    [[ -d ${p} ]] && unique_path -a ${p}
  done
}

if [ ${UID} -eq 0 ]; then
  unique_path -b ~root/bin
  # PATH=~root/bin:${PATH}
else
  add_paths_before_if ${HOME}/bin
  # MacPorts
  add_paths_before_if /opt/local/bin /opt/local/sbin
  [[ -d /opt/local/man ]] && unique_manpath -b /opt/local/man
  # Other installs
  add_paths_before_if /usr/local/bin /usr/local/sbin
  [[ -d /usr/local/man ]] && unique_manpath -b /usr/local/man
  # Local system git
  add_paths_before_if /usr/local/git/bin
  [[ -d /usr/local/git/man ]] && unique_manpath -b /usr/local/git/man

  if [ -x ${HOME}/usr/bin/git ]; then
    # Remove /usr/local/git, then add ${HOME}/usr/bin et al.
    clean_path /usr/local/git/bin
    unique_path -b ${HOME}/usr/bin
    unique_manpath -b ${HOME}/usr/share/man
    export GIT_EXEC_PATH="${HOME}/usr/bin"
  fi

  add_paths_before_if ${HOME}/bin
  add_paths_before_if ${HOME}/.dotfiles/bin
fi

# less options
export LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export ZMESSDIR=~/mess

# these are the default arguments to exuberant-ctags
# CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
