#! /bin/zsh

if has sudo; then
  function su() { export XAUTHORITY=${HOME}/.Xauthority; command sudo -s "${@}"; }
  function sudo() { export XAUTHORITY=${HOME}/.Xauthority; command sudo "${@}"; }
fi

alias du="du -hcs"
alias df="df -h"

alias ls="ls -F"
alias l="ls -lFh"
alias ll="ls -lAF"
alias la='ls -AF'
alias lla="ls -lAF"
alias lsf="ls -sF"
alias ltr="ls -ltrF"

function wt() { while true; do (${@}); sleep 1; clear; done; }

function bdiff() { diff "${1}" "${2}" || diff <(hex "${1}") <(hex "${2}"); }

function tohtml() {
  if [ -z ${1} ]; then
    echo "tohtml <file>" >&2
    return 1
  fi
  vim -e +:TOhtml +w +qa ${1}
}

function yyyymmdd() { date +%Y%m%d; }
function yyyymmdd-hhmmss() { date +%Y%m%d-%H%M%S; }
alias ymd=yyyymmdd
alias ymd-hms=yyyymmdd-hhmmss

if has mvim; then
  function gvman() { mvim --servername vman -c ":RMan ${*}" ; }
elif has gvim; then
  function gvman() { gvim --servername vman -c ":RMan ${*}" ; }
fi

has gvman && function mvman() { gvman ${*}; }

function vman() { vim -c ":RMan ${*}"; }
function vimgrep() { tmp="${@}"; vim -c "vimgrep ${tmp}"; }

if has xclip; then
  function xpwd() { echo ${PWD} | xclip -i; xclip -o; }
  function xcd() { cd `xclip -o`; }
fi

function sum() { SUM=0; while read NUM; do SUM=$((${SUM}+${NUM})); done; echo ${SUM}; }

# cdd x will do cd ../x but with an absolute path
function cdd() {
  local target
  target=$(dirname $(pwd))
  cd ${target}/${1}
}
alias ..='cd ..'

alias aliases=alias
alias h=history
alias j=jobs

alias cleanf='clean -f'
alias cleanrf='clean -rf'
alias keep='noglob keep'

# commands starting with % for pasting from web
alias %=' '

autoload zmv
alias mmv='noglob zmv -W'

cvi () { vim -O ${${1%.[hc]}%.}.{h,c}; }
xvi () { vim -O ${${${1%.h}%.cpp}%.}.{h,cpp}; }

if (has mvim); then
  cmvi () { mvim -O ${${1%.[hc]}%.}.{h,c}; }
  xmvi () { mvim -O ${${${1%.h}%.cpp}%.}.{h,cpp}; }
fi

# commands starting with % for pasting from web
alias %=' '

# Suffix aliases
alias -s rb=ruby
alias -s py=python

# alias -g CL="| wc -l"
# alias -g DN=/dev/null
# alias -g EG='|& egrep'
# alias -g EH='|& head'
# alias -g EL='|& less'
# alias -g ELS='|& less -S'
# alias -g ETL='|& tail -20'
# alias -g ET='|& tail'
# alias -g F=' | fmt -'
# alias -g G='| egrep'
# alias -g H='| head'
# alias -g HL='|& head -20'
# alias -g Sk="*~(*.bz2|*.gz|*.tgz|*.zip|*.z)"
# alias -g LL="2>&1 | less"
# alias -g L="| less"
# alias -g LS='| less -S'
# alias -g M='| more'
# alias -g NE="2> /dev/null"
# alias -g NS='| sort -n'
# alias -g NUL="> /dev/null 2>&1"
# alias -g PIPE='|'
# alias -g R=' > /c/aaa/tee.txt '
# alias -g RNS='| sort -nr'
# alias -g S='| sort'
# alias -g TL='| tail -20'
# alias -g T='| tail'
# alias -g US='| sort -u'
# alias -g VM=/var/log/messages
# alias -g X0G='| xargs -0 egrep'
# alias -g X0='| xargs -0'
# alias -g XG='| xargs egrep'
# alias -g X='| xargs'
