#!/bin/zsh

if is-interactive; then
  export PSSH_PWD="${HOME}/.ssh/pssh_pwd"
  alias pssh="fc -A; pwd > ${PSSH_PWD}; ssh"

  if [ -f "${PSSH_PWD}" -a x"${SSH_TTY}" != x ]; then
    dir=$(cat ${PSSH_PWD})
    cd $dir
    rm -f "${PSSH_PWD}"
    export PWD="$dir"
    exec ${SHELL:-/bin/zsh}
    echo "##### failed pssh thingy" >&2
  fi

  export SSH_ENV="${HOME}/.ssh/environment"
  function _start_ssh_agent
  {
    echo -n "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add
  }

  if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    [ -z "${SSH_AGENT_PID}" ] && _start_ssh_agent
    ps "${SSH_AGENT_PID}" > /dev/null || { _start_ssh_agent }
  else
    _start_ssh_agent
  fi

#   _real_ssh=$(which ssh)
#   if [ -n "$_real_ssh" ]; then
#     function ssh() {
#       if ( echo "$@" | grep -q "^\([^-]* \)\?\<tau\>" ) ; then
#         TERM=rxvt $_real_ssh $@
#       else
#         $_real_ssh $@
#       fi
#     }
#   fi
fi

if has autossh; then
  # http://noone.org/blog/English/Computer/Shell/Perfect%20Team:%20autossh%20and%20GNU%20Screen.futile
  function asc()
  {
    # Set the title to something more obvious, e.g. the expanded alias, eh,
    # function
    print -Pn "\e]0;%n@%m: autossh -t $* 'screen -RdU'\a";
    autossh -x -a -t "$@" 'screen -RdU'
  }

  compdef asc=ssh
fi
