#!/bin/zsh
#
# vi-mode colour changing
#   http://www.zsh.org/mla/users/2006/msg01196.html

setopt prompt_subst

autoload -U promptinit
promptinit

autoload is-at-least

baregit=$(whence -p git)

# Set up some basic vcs_info handling.
if is-at-least 4.3.6; then
  autoload -Uz vcs_info
  zstyle ':vcs_info:*' formats '%b '
  zstyle ':vcs_info:(svn|bzr|cvs):*' branchformat '%b:%r'
  zstyle ':vcs_info:cvs:*' branchformat '%r '
  zstyle ':vcs_info:bzr:*' use-simple true 
  zstyle ':vcs_info:git:*:*' command ${baregit:-git}
  zstyle ':vcs_info:*' enable git cvs svn hg bzr p4
  # vcs_info also needs to be in precmd, see: 10_hooks
  vcs_info
fi

# prompt austin
prompt austin2 noverbose
