#!/bin/zsh

function _plan9_env()
{
  local p9path
  for p9 in "${HOME}/.plan9" "${HOME}/plan9" /usr/local/plan9; do
    if [ -d "${p9}/bin" ]; then
      p9path="${p9}"
      break
    fi
  done

  if [ -n "${p9path}" ]; then
    PLAN9="${p9path}"
    export PLAN9
    PATH=${PATH}:"${PLAN9}/bin"
    export PATH
  fi
}

_plan9_env
