#! /bin/zsh

has nopaste && zsh_plugins+=(nopaste)
has vagrant && zsh_plugins+=(vagrant)

for plugin (${zsh_plugins}); do
  fpath=(~/.zsh/plugins/${plugin} ${fpath})
done

autoload -U $^fpath/*(N.:t)
