#! /bin/zsh

zmodload zsh/complist
autoload -U compinit 
compinit

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

zstyle ':completion:*' list-colors ''
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Fuzzy matching
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle -e ':completion:*:approximate:*' \
        max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3))numeric)'


zstyle ':completion:*:functions' ignored-patterns '_*'

zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always

zstyle ':completion:*:cd:*' ignore-parents parent pwd

zle -C insert-kept-result complete-word _generic
zle -C expand-kept-result complete-word _generic
zle -C _expand_word complete-word _expand_word_and_keep      

zstyle ':completion:*' insert-kept all
zstyle ':completion:insert-kept-result:*' completer _insert_kept
zstyle ':completion:expand-kept-result:*' completer _insert_kept

bindkey '^Xk' insert-kept-result
bindkey '^XK' expand-kept-result
