#! /bin/zsh

# Updated to include changes based on what I expect and what I cribbed from
# Chris Neukirchen.

autoload colors zsh/terminfo
[[ "${terminfo[colors]}" -ge 8 ]] && colors

setopt prompt_subst
autoload -U promptinit && promptinit

prompt austin
