#! /bin/zsh

# Updated to include changes based on what I expect and what I cribbed from
# Chris Neukirchen.

autoload colors zsh/terminfo
[[ "${terminfo[colors]}" -ge 8 ]] && colors

if [[ -n ${SSH_CONNECTION} ]]; then
  export PS1='%m:%3~$(git_info_for_prompt)%# '
else
  export PS1='%3~$(git_info_for_prompt)%# '
fi

export ZMESSDIR=~/mess

# export EDITOR='mate -w'
export EDITOR='mvim'

export PATH=${HOME}/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/git/bin:${PATH}
export MANPATH=/usr/local/man:/opt/local/man:/usr/local/git/man:${MANPATH}

fpath=(~/.zsh/functions ~/.zsh/git/functions ${fpath})
autoload -U ~/.zsh/functions/*(:t)

HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

setopt BASH_AUTO_LIST
setopt AUTO_MENU
setopt NO_ALWAYS_LAST_PROMPT
setopt NO_LIST_BEEP

setopt NO_BG_NICE # don't nice background tasks
setopt NO_HUP

setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS # allow functions to have local traps
setopt HIST_VERIFY
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
# setopt IGNORE_EOF # disables '^D' to logout

setopt APPEND_HISTORY # adds history
setopt INC_APPEND_HISTORY SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history
setopt extended_glob

zle -N newtab
zle -N rationalise_dot

bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[[5D' beginning-of-line
bindkey '^[[5C' end-of-line
bindkey '^[[3~' delete-char
bindkey '^[^N' newtab
bindkey '^?' backward-delete-char 

bindkey . rationalise_dot

# Z line editor, zsh’s version of readline has a very good Emacs keybinding
# support which we’ll enable and configure it to regard / as a word seperator
# too (highly useful for editing paths):
WORDCHARS=${WORDCHARS//[&=\/;!#%\{]}
bindkey -e

setopt prompt_subst
autoload -U promptinit && promptinit

prompt austin
