#!/bin/bash

rm rvm-install.log

for target in ree kiji jruby jruby-head macruby maglev maglev-head rbx ruby-1.8.7-head ruby-1.8.7 ruby-1.9.2-head ruby-1.9.2 ruby-1.9.3-head ruby-1.9.3 ruby-head; do
  case $target in
    ree|kiji)
      export CC=/usr/bin/gcc-4.2
      export CXX=/usr/bin/g++-4.2
      ;;
    *)
      unset CC CXX
      ;;
  esac

  {
    echo "=====> Installing $target <====="
    rvm install $target
  } 2>&1 | tee -a rvm-install.log
done
