#! /bin/zsh

mysql_bin=$(dirname "$(which-mysql)")
add-paths-after-if ${mysql_bin}

if is-mac; then
  mysql_lib="$(dirname "${mysql_bin}")/lib"
  export DYLD_LIBRARY_PATH=${mysql_lib}:${DYLD_LIBRARY_PATH}
fi
