#! zsh

function()
{
  add-paths-before-if ${HOME}/.brew/bin

  local prefix="$(brew --prefix)"

  add-paths-after-if "${prefix}/bin" "${prefix}/sbin"

  local cf="${prefix}/Library/Contributions/brew_zsh_completion.zsh"
  [ -f "${cf}" ] && autoload -U "${cf}"

  [ -x $(brew --prefix)/bin/node ] && NODE_PATH="${prefix}/lib/node_modules"
}
