#!/bin/bash

# changing directory to code project
# function c { cd ~/code/$1; }

# alternative to "rails" command to use templates
# function railsapp {
#   template=$1
#   appname=$2
#   shift 2
#   rails $appname -m http://github.com/ryanb/rails-templates/raw/master/$template.rb $@
# }

[ -r ${HOME}/.zsh/aliases ] && source ~/.zsh/aliases

# misc
alias reload='source ${HOME}/.bash_profile'
