#! zsh

if [ -n "${FULLNAME}" ]; then
  export GIT_AUTHOR_NAME="${FULLNAME}"
  export GIT_COMMITTER_NAME="${FULLNAME}"
else
  export GIT_AUTHOR_EMAIL="${EMAIL}"
  export GIT_COMMITTER_EMAIL="${EMAIL}"
fi

# Various git scripts

function gitize()
{
  if [ ${#} -ne 0 ]; then
    message="${*}"
  else
    message="Initial commit"
  fi

  git init && \
    git add . && \
    git commit -a -m "${message}" && \
    git gc
}
