#! zsh

if [ -n "${FULLNAME}" ]; then
  export GIT_AUTHOR_NAME="${FULLNAME}"
  export GIT_COMMITTER_NAME="${FULLNAME}"
fi

if [ -n "${EMAIL}" ]; then
  export GIT_AUTHOR_EMAIL="${EMAIL}"
  export GIT_COMMITTER_EMAIL="${EMAIL}"
fi

add-paths-before-if --manpath ${current_plugin_path}/share/man

# Various git scripts

export __hzsh_git_plugin_identity_path="${current_plugin_path}/identities"
